//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XptoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeRole
    {
        public int EmployeeId { get; set; }
        public int RoleId { get; set; }
        public bool Deleted { get; set; }
        public int ModifiedBy { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
